# Site settings:
title: The Regal Internet Brothers
description: >
  This is a blog created by The Regal Internet Brothers, used to document projects, and post related news.
baseurl: "" # Sub-path.
url: "http://Regal-Internet-Brothers.github.io" # Hostname + Protocol
twitter_username: ImmutableOctet
github_username: Regal-Internet-Brothers

# Build settings:
markdown: kramdown
